### ISSUE TITLE
Rename "Robot" to RobotFunction

### ISSUE THREAD

**Issue by ysakthi** [titan2022/RobotExample#7]
because it sounds cooler

**Comment by Tneidlein** [comment]
This triggers me hardcore.

**Comment by Tneidlein** [comment]
https://www.google.com/imgres?imgurl=https%3A%2F%2Fi0.wp.com%2Fwww.takethis.org%2Fwp-content%2Fuploads%2F2016%2F04%2Ftriggered-meme.jpg%3Ffit%3D850%252C297&imgrefurl=http%3A%2F%2Fwww.takethis.org%2F2016%2F04%2Ftriggered-a-personal-response-to-a-popular-meme%2F&docid=C-7GhzFpa1-WXM&tbnid=80IAhyjiOSnjDM%3A&vet=1&w=850&h=297&bih=600&biw=1280&ved=0ahUKEwjPnZ--yuPQAhVKq1QKHSMDCCkQMwg0KAMwAw&iact=mrc&uact=8
